training_data_paths:
- "/mnt/data_1/home_tsteam/scaling_tsfm/CauKer1000H1M.arrow"
probability:
- 1



# training_data_paths:
#   - "/mnt/data_1/home_tsteam/scaling_tsfm/CauKer200K_Kernel1_Parent0.arrow"
#   - "/mnt/data_1/home_tsteam/scaling_tsfm/CauKer200K_Kernel2_Parent1.arrow"
#   - "/mnt/data_1/home_tsteam/scaling_tsfm/CauKer200K_Kernel3_Parent2.arrow"
#   - "/mnt/data_1/home_tsteam/scaling_tsfm/CauKer200K_Kernel4_Parent3.arrow"
#   - "/mnt/data_1/home_tsteam/scaling_tsfm/CauKer200K_Kernel5_Parent4.arrow"

# probability:
#   - 1
#   - 1
#   - 1
#   - 1
#   - 1
context_length: 512
prediction_length: 64
min_past: 60
max_steps: 200_000
save_steps: 100_000
log_steps: 500
per_device_train_batch_size: 64
learning_rate: 0.001
optim: adamw_torch_fused
num_samples: 20
shuffle_buffer_length: 100_000
gradient_accumulation_steps: 1
model_id: google/t5-efficient-small
model_type: seq2seq
random_init: true
tie_embeddings: true
output_dir: ./output/
tf32: true
torch_compile: true
tokenizer_class: "MeanScaleUniformBins"
tokenizer_kwargs:
  low_limit: -15.0
  high_limit: 15.0
n_tokens: 4096
lr_scheduler_type: linear
warmup_ratio: 0.0
dataloader_num_workers: 1
max_missing_prop: 0.9
use_eos_token: true
